AWSTemplateFormatVersion: 2010-09-09
Resources:
 SampleLambda:        
        Type: "AWS::Lambda::Function"
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: nodejs14.x
            CodeUri: ./DemoLambda
            Description: Lambda function for CD Demo
            MemorySize: 500
            Timeout: 30
            Role: arn:aws:iam::716262823751:role/Lambda-test-saurabh
