AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Sereverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./LambdaCode
      Description: Lambda function for CD Demo
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::716262823751:role/Lambda-test-saurabh
      Environment:
        variables:
          REGION: ap-northeast-1
