AWSTemplateFormatVersion: '2010-09-09'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: nodejs14.x
      Code:
        S3Bucket: meteor-350-1
        S3Key: data/test.zip
      Description: Lambda function for CD Demo
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::716262823751:role/Lambda-test-saurabh
