AWSTemplateFormatVersion: '2010-09-09'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./CodeLambda
      Description: Lambda function for CD Demo
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::716262823751:role/Lambda-test-saurabh
